#!/bin/bash
# Version guard and build-version generator.
#
#   version.sh                  write build/generated/Version.xcconfig
#   version.sh --check          every v* tag on HEAD must be v<VERSION>
#   version.sh --check-tag TAG  TAG must be v<VERSION>
#
# Works on the git repository containing the current directory, not on the
# script's own checkout. Runs on macOS /bin/bash 3.2 and on Linux bash.
set -euo pipefail

die() {
	echo "version.sh: $*" >&2
	exit 1
}

usage() {
	die "usage: version.sh [--check | --check-tag <tag>]"
}

root=$(git rev-parse --show-toplevel 2>/dev/null) || die "not inside a git repository"

read_version() {
	[ -f "$root/VERSION" ] || die "VERSION file is missing"
	local v
	# Trim surrounding whitespace only; anything inside must still match.
	v=$(sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' <"$root/VERSION" | sed -e '/^$/d')
	[[ "$v" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || die "VERSION '$v' is not MAJOR.MINOR.PATCH"
	echo "$v"
}

check_head_tags() {
	local version tags tag
	version=$(read_version)
	git -C "$root" rev-parse --verify -q HEAD >/dev/null || die "repository has no commits"
	tags=$(git -C "$root" tag --points-at HEAD --list 'v*') || die "could not list tags on HEAD"
	for tag in $tags; do
		[ "$tag" = "v$version" ] || die "tag $tag on HEAD does not match VERSION $version"
	done
}

check_tag() {
	local version
	version=$(read_version)
	[ "$1" = "v$version" ] || die "tag $1 does not match VERSION $version (expected v$version)"
}

generate() {
	local version build commit out_dir out tmp
	version=$(read_version)
	git -C "$root" rev-parse --verify -q HEAD >/dev/null || die "repository has no commits"

	if [ -n "${EIKON_BUILD_NUMBER:-}" ]; then
		[[ "$EIKON_BUILD_NUMBER" =~ ^[0-9]+$ ]] && [ "$EIKON_BUILD_NUMBER" -gt 0 ] ||
			die "EIKON_BUILD_NUMBER '$EIKON_BUILD_NUMBER' is not a positive integer"
		build=$EIKON_BUILD_NUMBER
	else
		if [ "$(git -C "$root" rev-parse --is-shallow-repository)" = "true" ]; then
			die "shallow clone: the commit count would be wrong; use a full clone (fetch-depth: 0) or set EIKON_BUILD_NUMBER"
		fi
		build=$(git -C "$root" rev-list --count HEAD)
	fi

	commit=$(git -C "$root" rev-parse --short HEAD)
	git -C "$root" update-index -q --refresh >/dev/null 2>&1 || true
	local status=0
	git -C "$root" diff-index --quiet HEAD -- || status=$?
	case $status in
	0) ;;
	1) commit="$commit-dirty" ;;
	*) die "could not check for uncommitted changes" ;;
	esac

	out_dir="$root/build/generated"
	out="$out_dir/Version.xcconfig"
	mkdir -p "$out_dir"
	tmp=$(mktemp "$out_dir/.Version.xcconfig.XXXXXX")
	trap 'rm -f "$tmp"' EXIT
	cat >"$tmp" <<EOF
// Generated by scripts/version.sh. Do not edit.
MARKETING_VERSION = $version
CURRENT_PROJECT_VERSION = $build
EIKON_GIT_COMMIT = $commit
EOF
	chmod 644 "$tmp"
	mv -f "$tmp" "$out"
	trap - EXIT
	echo "Wrote $out ($version, build $build, $commit)"
}

case $# in
0) generate ;;
1)
	case $1 in
	--check) check_head_tags ;;
	*) usage ;;
	esac
	;;
2)
	case $1 in
	--check-tag) check_tag "$2" ;;
	*) usage ;;
	esac
	;;
*) usage ;;
esac
